# Generated by Django 5.1.5 on 2025-01-27 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_pic_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
