# Generated by Django 5.0.4 on 2024-12-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("salon", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="salon",
            name="description",
        ),
        migrations.AlterField(
            model_name="message",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="salon",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
