# Generated by Django 5.0.4 on 2025-01-13 13:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("salon", "0003_alter_message_salon"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="salon",
        ),
        migrations.RemoveField(
            model_name="message",
            name="user",
        ),
    ]
