# Generated by Django 5.0.4 on 2024-12-22 13:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nom", models.CharField(max_length=255)),
                ("prenom", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=255)),
                (
                    "photo",
                    models.ImageField(default="default.jpg", upload_to="profile_pics"),
                ),
            ],
        ),
    ]
